# fly.toml app configuration file generated for my-app on 2023-12-08T11:04:43+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-app"
primary_region = "ord"

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
